export const rag_ratings = [
  {prob_rating: 1, severity_rating: 1, rag_rating: 1},
  {prob_rating: 2, severity_rating: 1, rag_rating: 1},
  {prob_rating: 3, severity_rating: 1, rag_rating: 1},
  {prob_rating: 4, severity_rating: 1, rag_rating: 1},
  {prob_rating: 5, severity_rating: 1, rag_rating: 2},
  {prob_rating: 1, severity_rating: 2, rag_rating: 1},
  {prob_rating: 2, severity_rating: 2, rag_rating: 1},
  {prob_rating: 3, severity_rating: 2, rag_rating: 2},
  {prob_rating: 4, severity_rating: 2, rag_rating: 2},
  {prob_rating: 5, severity_rating: 2, rag_rating: 3},
  {prob_rating: 1, severity_rating: 3, rag_rating: 1},
  {prob_rating: 2, severity_rating: 3, rag_rating: 2},
  {prob_rating: 3, severity_rating: 3, rag_rating: 2},
  {prob_rating: 4, severity_rating: 3, rag_rating: 3},
  {prob_rating: 5, severity_rating: 3, rag_rating: 4},
  {prob_rating: 1, severity_rating: 4, rag_rating: 2},
  {prob_rating: 2, severity_rating: 4, rag_rating: 3},
  {prob_rating: 3, severity_rating: 4, rag_rating: 3},
  {prob_rating: 4, severity_rating: 4, rag_rating: 4},
  {prob_rating: 5, severity_rating: 4, rag_rating: 4},
  {prob_rating: 1, severity_rating: 5, rag_rating: 3},
  {prob_rating: 2, severity_rating: 5, rag_rating: 3},
  {prob_rating: 3, severity_rating: 5, rag_rating: 4},
  {prob_rating: 4, severity_rating: 5, rag_rating: 4},
  {prob_rating: 5, severity_rating: 5, rag_rating: 4}
];
