export const riskLevels = [
  {prob: 1, sev: 1, level: 1},
  {prob: 2, sev: 1, level: 1},
  {prob: 3, sev: 1, level: 1},
  {prob: 4, sev: 1, level: 1},
  {prob: 5, sev: 1, level: 2},
  {prob: 1, sev: 2, level: 1},
  {prob: 2, sev: 2, level: 1},
  {prob: 3, sev: 2, level: 2},
  {prob: 4, sev: 2, level: 2},
  {prob: 5, sev: 2, level: 3},
  {prob: 1, sev: 3, level: 1},
  {prob: 2, sev: 3, level: 2},
  {prob: 3, sev: 3, level: 2},
  {prob: 4, sev: 3, level: 3},
  {prob: 5, sev: 3, level: 4},
  {prob: 1, sev: 4, level: 2},
  {prob: 2, sev: 4, level: 3},
  {prob: 3, sev: 4, level: 3},
  {prob: 4, sev: 4, level: 4},
  {prob: 5, sev: 4, level: 4},
  {prob: 1, sev: 5, level: 3},
  {prob: 2, sev: 5, level: 3},
  {prob: 3, sev: 5, level: 4},
  {prob: 4, sev: 5, level: 4},
  {prob: 5, sev: 5, level: 4}
];
