export const risks = [
  {
    "risk_ID": "1",
    "id": "P1",
    "name": "Premium",
    "description": "Premium different to expectations.",
    "prob_rating": "5",
    "severity_rating": "4",
    "reputation_rating": "1",
    "rag_rating": "4",
    "loss": "1",
    "risk_level": "1",
    "company": "UK Club",
    "department": "Underwriting",
    "process": null,
    "created_at": "2021-01-01 08:27:22",
    "modified_at": "2021-01-01 08:27:22"
  },
  {
    "risk_ID": "2",
    "id": "P2",
    "name": "Premium volumes",
    "description": "Premium volume different to expectations.",
    "prob_rating": "3",
    "severity_rating": "3",
    "reputation_rating": "3",
    "rag_rating": "2",
    "loss": "1",
    "risk_level": "2",
    "company": "UK Club",
    "department": "Underwriting",
    "process": null,
    "created_at": "2021-01-01 08:27:22",
    "modified_at": "2021-01-01 08:27:22"
  },
  {
    "risk_ID": "3",
    "id": "P3",
    "name": "Premium adequacy",
    "description": "Premium adequacy different to expectations.",
    "prob_rating": "5",
    "severity_rating": "5",
    "reputation_rating": "2",
    "rag_rating": "4",
    "loss": "1",
    "risk_level": "2",
    "company": "UK Club",
    "department": "Underwriting",
    "process": null,
    "created_at": "2021-01-01 08:27:22",
    "modified_at": "2021-01-01 08:27:22"
  },
  {
    "risk_ID": "4",
    "id": "C1",
    "name": "Claims",
    "description": "Claims different to expectations.",
    "prob_rating": "4",
    "severity_rating": "5",
    "reputation_rating": "3",
    "rag_rating": "4",
    "loss": "1",
    "risk_level": "1",
    "company": "UK Club",
    "department": "Claims",
    "process": null,
    "created_at": "2021-01-01 08:27:22",
    "modified_at": "2021-01-01 08:27:22"
  },
  {
    "risk_ID": "24",
    "id": "I1",
    "name": "Investment",
    "description": "Investment return different to expectations.",
    "prob_rating": "4",
    "severity_rating": "5",
    "reputation_rating": "2",
    "rag_rating": "4",
    "loss": "0",
    "risk_level": "1",
    "company": "UK Club",
    "department": null,
    "process": null,
    "created_at": "2021-01-08 18:22:33",
    "modified_at": "2021-01-08 18:22:33"
  }
];
